import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { afterEach, test } from 'node:test';

const scriptSourcePath = new URL('./generate-supabase-api.mjs', import.meta.url);
const tempRoots = [];

const makeTempRoot = async (name) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), `supabase-api-gen-${name}-`));
  tempRoots.push(root);
  return root;
};

afterEach(async () => {
  while (tempRoots.length > 0) {
    const root = tempRoots.pop();
    await fs.rm(root, { recursive: true, force: true });
  }
});

const setupWorkspaceFixture = async () => {
  const root = await makeTempRoot('workspace');
  const workspaceRoot = path.join(root, 'workspace');
  const scriptDir = path.join(workspaceRoot, 'lib', 'scripts');
  const generatedDir = path.join(workspaceRoot, 'lib', 'api-client-react', 'src', 'generated');
  const functionsDir = path.join(workspaceRoot, 'supabase', 'functions');

  await fs.mkdir(scriptDir, { recursive: true });
  await fs.mkdir(generatedDir, { recursive: true });
  await fs.mkdir(functionsDir, { recursive: true });
  await fs.copyFile(scriptSourcePath, path.join(scriptDir, 'generate-supabase-api.mjs'));

  return {
    workspaceRoot,
    functionsDir,
    generatedDir,
    scriptPath: path.join(scriptDir, 'generate-supabase-api.mjs'),
  };
};

const runGenerator = async (scriptPath) => {
  const child = spawn(process.execPath, [scriptPath], {
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  let stdout = '';
  let stderr = '';
  child.stdout.setEncoding('utf8');
  child.stderr.setEncoding('utf8');
  child.stdout.on('data', (chunk) => {
    stdout += chunk;
  });
  child.stderr.on('data', (chunk) => {
    stderr += chunk;
  });

  const code = await new Promise((resolve, reject) => {
    child.on('error', reject);
    child.on('close', resolve);
  });

  return { code, stdout, stderr };
};

test('generator emits query helpers for GET contracts without request bodies', async () => {
  const { functionsDir, generatedDir, scriptPath } = await setupWorkspaceFixture();
  const contractDir = path.join(functionsDir, 'get-status');
  await fs.mkdir(contractDir, { recursive: true });
  await fs.writeFile(
    path.join(contractDir, 'contract.ts'),
    `export interface GetStatusResponse {
  status: string
}

export const getStatusContract = {
  name: 'get-status',
  method: 'GET',
  path: '/functions/v1/get-status',
  responseTypeName: 'GetStatusResponse',
  responseShape: {
    status: 'string',
  },
} as const
`,
    'utf8',
  );

  const result = await runGenerator(scriptPath);
  assert.equal(result.code, 0, result.stderr);

  const apiSource = await fs.readFile(path.join(generatedDir, 'api.ts'), 'utf8');
  const endpointsSource = await fs.readFile(path.join(generatedDir, 'endpoints.ts'), 'utf8');
  const typesSource = await fs.readFile(path.join(generatedDir, 'types.ts'), 'utf8');
  const runtimeSource = await fs.readFile(path.join(generatedDir, 'runtime.ts'), 'utf8');
  const indexSource = await fs.readFile(path.join(generatedDir, 'index.ts'), 'utf8');
  const routeManifest = await fs.readFile(path.join(generatedDir, 'spec', 'route-manifest.json'), 'utf8');
  const openApi = await fs.readFile(path.join(generatedDir, 'spec', 'edge-functions.openapi.json'), 'utf8');
  assert.match(apiSource, /^\/\/ AUTO-GENERATED FILE\. DO NOT EDIT\.\n\/\/ Generated by: pnpm gen:supabase-api\n/m);
  assert.match(endpointsSource, /^\/\/ AUTO-GENERATED FILE\. DO NOT EDIT\.\n\/\/ Generated by: pnpm gen:supabase-api\n/m);
  assert.match(typesSource, /^\/\/ AUTO-GENERATED FILE\. DO NOT EDIT\.\n\/\/ Generated by: pnpm gen:supabase-api\n/m);
  assert.match(runtimeSource, /^\/\/ AUTO-GENERATED FILE\. DO NOT EDIT\.\n\/\/ Generated by: pnpm gen:supabase-api\n/m);
  assert.match(indexSource, /^\/\/ AUTO-GENERATED FILE\. DO NOT EDIT\.\n\/\/ Generated by: pnpm gen:supabase-api\n/m);
  assert.match(routeManifest, /^\{\n  \"_generated\": \"AUTO-GENERATED FILE\. DO NOT EDIT\. Generated by pnpm gen:supabase-api\"/m);
  assert.match(openApi, /^\{\n  \"_generated\": \"AUTO-GENERATED FILE\. DO NOT EDIT\. Generated by pnpm gen:supabase-api\"/m);
  assert.match(apiSource, /import \{ invokeGeneratedFunction, type GeneratedFunctionInvokeInit \} from '\.\/runtime';/);
  assert.match(apiSource, /export async function callGetStatus\(init\?: GeneratedFunctionInvokeInit\): Promise<GetStatusResponse>/);
  assert.match(apiSource, /export function useGetStatusQuery\(/);
  assert.match(apiSource, /return invokeGeneratedFunction<GetStatusResponse>\(\{/);
  assert.match(apiSource, /functionName: 'get-status'/);
  assert.match(apiSource, /method: 'GET'/);
  assert.doesNotMatch(apiSource, /customFetch</);
  assert.doesNotMatch(apiSource, /JSON\.stringify\(body\)/);
  assert.doesNotMatch(apiSource, /mutationFn: \(body\) => callGetStatus\(body\)/);
});

test('generator keeps mutation helpers for contracts with explicit request bodies', async () => {
  const { functionsDir, generatedDir, scriptPath } = await setupWorkspaceFixture();
  const contractDir = path.join(functionsDir, 'create-foo');
  await fs.mkdir(contractDir, { recursive: true });
  await fs.writeFile(
    path.join(contractDir, 'contract.ts'),
    `export interface CreateFooRequest {
  name: string
}

export interface CreateFooResponse {
  id: string
}

export const createFooContract = {
  name: 'create-foo',
  method: 'POST',
  path: '/functions/v1/create-foo',
  requestTypeName: 'CreateFooRequest',
  requestShape: {
    name: 'string',
  },
  responseTypeName: 'CreateFooResponse',
  responseShape: {
    id: 'string',
  },
} as const
`,
    'utf8',
  );

  const result = await runGenerator(scriptPath);
  assert.equal(result.code, 0, result.stderr);

  const apiSource = await fs.readFile(path.join(generatedDir, 'api.ts'), 'utf8');
  const runtimeSource = await fs.readFile(path.join(generatedDir, 'runtime.ts'), 'utf8');
  assert.match(apiSource, /export async function callCreateFoo\(body: CreateFooRequest, init\?: GeneratedFunctionInvokeInit\): Promise<CreateFooResponse>/);
  assert.match(apiSource, /functionName: 'create-foo'/);
  assert.match(apiSource, /body,/);
  assert.doesNotMatch(apiSource, /,,/);
  assert.match(runtimeSource, /export function setGeneratedSupabaseClient/);
  assert.match(runtimeSource, /export async function invokeGeneratedFunction/);
  assert.match(runtimeSource, /invokeSupabaseFunction<TResponse>/);
  assert.match(apiSource, /export function useCreateFooMutation\(/);
});
